ysudo: required
dist: trusty
language: java
notifications:
  slack: cvtron:zpn5EYMgd1chDwtF1goXhpyb#bots
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8
node_js:
  - 7
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 6.9.5
  - npm install -g yarn
  - npm install -g coveralls
install:
  - travis_wait 60 yarn install
script:
  - yarn test